routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
Route::post('/dashboard/top-grossing-products', 'DashboardController@top_grossing_products')->name('dashboard.top_grossing_products');
Route::post('/dashboard/top-selling-products', 'DashboardController@top_selling_products')->name('dashboard.top_selling_products');
Route::post('/dashboard/sales-gross-chart', 'DashboardController@sales_gross_chart')->name('dashboard.sales_gross_chart');
Route::post('/dashboard/device-sales', 'DashboardController@device_sales')->name('dashboard.device_sales');
Route::get('/dashboard/export-devices-csv', 'DashboardController@export_devices_csv')->name('dashboard.export_devices_csv');

Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

Route::get('/devices/export', 'DeviceController@export')->name('devices.export');
Route::resource('devices', 'DeviceController');

Route::resource('users', 'UserController', ['except' => ['create', 'store']]);

Route::get('/devicegroups/export', 'DeviceGroupController@export')->name('devicegroups.export');
Route::resource('devicegroups', 'DeviceGroupController');


Route::resource('usergroups', 'UserGroupController');

Route::get('/sales/{sale}/download', 'SaleController@download')->name('sales.download');
Route::get('/sales/export', 'SaleController@export')->name('sales.export');
Route::resource('sales', 'SaleController', ['only' => ['index', 'show']]);

Route::get('/products/export', 'ProductController@export')->name('products.export');
Route::resource('products', 'ProductController', ['only' => ['index', 'show']]);

app/User.php
<?php

namespace App;

use App\Sale;
use App\Device;
use Carbon\Carbon;
use App\Traits\HasUuid;
use App\Traits\HasApiKey;
use QCod\ImageUp\HasImageUploads;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HasImageUploads;
    use HasUuid;
    use HasApiKey;

    public $incrementing = false;

    public $api_key_field = 'api_token';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'device_limit', 'is_active', 'picture'
    ];

    protected static $imageFields = [
        'picture' => [
            'width' => 512,
            
            'height' => 512,

            'crop' => True,

            'disk' => 'public',

            'rules' => 'image|max:5000',

            'path' => 'profile_pictures',

            'placeholder' => '/images/prev.jpg',
        ]
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function devices()
    {
        return $this->hasMany(Device::class, 'user_id', 'id');
    }

    public function sales()
    {
        return $this->hasManyThrough(Sale::class, Device::class);
    }

    public function getLastLoginAttribute()
    {
        return Carbon::createFromTimeStamp(strtotime($this->last_login_at))->diffForHumans();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\AdminUpdateUserRequest;

class UserController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withCount('devices')->get();
        return view('users.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $user->load(['devices', 'devices.device_groups']);
        return view('users.show', compact("user"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact("user"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUpdateUserRequest $request,User $user)
    {
        $input = $request->validated();
        $user->fill($input)->save();
        return redirect()->route('users.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user == Auth::user()->id) {
            return redirect()->back()->withErrors(['user' => 'Cannot delete that user'])->withInput();
        }
        return redirect()->route('users.index');
    }
}

resources/views/users/edit.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="company name">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">edit {{$user->name}}</h3>
                            </div>
                            <form method="POST" action="{{ route('users.update', $user) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                @include('includes.forminputfields',['fieldname' => 'device_limit', 'fieldlabel' => 'Device limit', 'fieldtype' => 'number','fielddefault' => $user->device_limit > 0 ? $user->device_limit : '', 'attributes' => 'required autofocus min="1" step-size="1"'])

                                @include('includes.forminputfields',[
                                    'fieldname' => 'is_active',
                                    'fieldtype' => 'select',
                                    'fieldlabel' => 'Status',
                                    'fielddefault' => $user->status,
                                    'fieldoptions' => [
                                        '0' => 'Disabled',
                                        '1' => 'Active'
                                    ],
                                    'attributes' => 'required'
                                ])

                                {{-- <div class="form-group row">
                                    <p class="text-center">
                                        @if ($errors->has('group_ids.*'))
                                            <span class="text-danger error">
                                                <strong>{{ $errors->first('group_ids.*') }}</strong>
                                            </span>
                                        @endif
                                    </p>
                                    <div class="table-responsive m-b-40">
                                        <table class="table table-borderless table-data2 datatable">
                                            <thead>
                                                <tr>
                                                    <th>Assign to User Groups</th>
                                                    <th>Created by</th>
                                                    <th>user count</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @for ($i = 0; $i < 5; $i++)
                                                    <tr>
                                                        <td>
                                                            <div class="form-group row">
                                                                <div class="col-md-1">
                                                                    <input id="group{{$i}}" type="checkbox" class="form-check-input" name="group{{$i}}" value="{{$i}}">
                                                                </div>
                                                                <label for="group{{$i}}" class="form-check-label col-md-4"> Group {{$i + 1}} </label>
                                                            </div>
                                                        </td>
                                                        <td>User 1</td>
                                                        <td>3</td>
                                                    </tr>
                                                @endfor
                                            </tbody>
                                        </table>
                                    </div>
                                </div> --}}

                                @include('includes.forminputfields',['fieldtype' => 'submit', 'fieldlabel' => 'Edit user'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.admin')

@section('admincontent')

<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">Users</h3>
        
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2 datatable">
                <thead>
                    <tr>
                        <th>name</th>
                        <th>email</th>
                        <th>groups</th>
                        <th>Status</th>
                        <th>devices</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                        <tr class="tr-shadow">
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>
                                <ul>
                                    <li><span class="block-email">Super Admin</span></li>
                                    <li><span class="block-email">Group admin</span></li>
                                    <li><span class="block-email">Device admin</span></li>
                                </ul>
                            </td>
                            <td>
                                <span class="status--{{$user->is_active ? 'process' : 'denied'}}">{{$user->is_active ? 'Active' : 'Disabled'}}</span>
                            </td>
                            <td>{{$user->devices_count}}</td>
                            <td>
                                <div class="table-data-feature">
                                    <a href="{{route('users.edit', $user)}}" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                        <i class="zmdi zmdi-edit"></i>
                                    </a>
                                    <form action="{{route('users.destroy',$user)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                            <i class="zmdi zmdi-delete"></i>
                                        </button>
                                    </form>
                                    <a href="{{route('users.show', $user)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                        <i class="zmdi zmdi-more"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.admin')

@section('admincontent')
<h3 class="title-5">{{$user->name}}</h3>
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-user"></i>
                            <strong class="card-title pl-2">Profile</strong>
                        </div>
                        <div class="card-body">
                            <div class="mx-auto d-block">
                                <img class="rounded-circle mx-auto d-block" src="{{$user->imageUrl('picture')}}" alt="Card image cap">
                                <h3 class="text-sm-center mt-2 mb-1 title-1">{{$user->name}}</h3>
                                <div class="location text-sm-center"><i class="fa fa-envelope"></i> {{$user->email}}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <!-- TOP CAMPAIGN-->
                    <div class="top-campaign">
                        <h3 class="title-3 m-b-30">{{$user->name}}</h3>
                        <div class="table-responsive">
                            <table class="table table-top-campaign">
                                <tbody>
                                    <tr>
                                        <td>Name</td>
                                        <td>{{$user->name}}</td>
                                    </tr>
                                    <tr>
                                        <td>Status</td>
                                        <td>
                                            <span class="status--{{$user->is_active ? 'process' : 'denied'}}">{{$user->is_active ? 'Active' : 'Disabled'}}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Device limit</td>
                                        <td>{{$user->device_limit > 0 ? $user->device_limit : 'Not set'}}</td>
                                    </tr>
                                    <tr>
                                        <td>Devices</td>
                                        <td>{{$user->devices->count()}}</td>
                                    </tr>
                                    <tr>
                                        <td>Date added</td>
                                        <td>{{$user->created_at}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center">
                            <a class="au-btn au-btn-icon au-btn--blue2 au-btn--small" href="{{route('users.edit', $user)}}"><i class="zmdi zmdi-edit"></i>edit user</a>
                        </div>
                    </div>
                    <!-- END TOP CAMPAIGN-->
                </div>
            </div>
        </div>
    </div>
</div>

@include('includes.devices', ['devices' => $user->devices, 'hide_add_device_link' => true])
@endsection