routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
Route::post('/dashboard/top-grossing-products', 'DashboardController@top_grossing_products')->name('dashboard.top_grossing_products');
Route::post('/dashboard/top-selling-products', 'DashboardController@top_selling_products')->name('dashboard.top_selling_products');
Route::post('/dashboard/sales-gross-chart', 'DashboardController@sales_gross_chart')->name('dashboard.sales_gross_chart');
Route::post('/dashboard/device-sales', 'DashboardController@device_sales')->name('dashboard.device_sales');
Route::get('/dashboard/export-devices-csv', 'DashboardController@export_devices_csv')->name('dashboard.export_devices_csv');

Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

Route::get('/devices/export', 'DeviceController@export')->name('devices.export');
Route::resource('devices', 'DeviceController');

Route::resource('users', 'UserController', ['except' => ['create', 'store']]);

Route::get('/devicegroups/export', 'DeviceGroupController@export')->name('devicegroups.export');
Route::resource('devicegroups', 'DeviceGroupController');


Route::resource('usergroups', 'UserGroupController');

Route::get('/sales/{sale}/download', 'SaleController@download')->name('sales.download');
Route::get('/sales/export', 'SaleController@export')->name('sales.export');
Route::resource('sales', 'SaleController', ['only' => ['index', 'show']]);

Route::get('/products/export', 'ProductController@export')->name('products.export');
Route::resource('products', 'ProductController', ['only' => ['index', 'show']]);

app/Device.php
<?php

namespace App;

use App\Sale;
use App\User;
use App\DeviceGroup;
use App\Traits\HasUuid;
use App\Traits\HasApiKey;
use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    use HasUuid;
    use HasApiKey;

    public $incrementing = false;
    
    public $api_key_field = 'api_token';

    protected $fillable = ['name', 'is_active'];

    protected $hidden = ['api_token'];

    public function device_groups()
    {
        return $this->belongsToMany(DeviceGroup::class, 'devices_device_groups', 'device_id', 'device_group_id');
    }

    public function sales()
    {
        return $this->hasMany(Sale::class, 'device_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use App\Device;
use App\DeviceGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\CreateOrUpdateDeviceRequest;
use Response;

class DeviceController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $devices = Device::with(['device_groups', 'sales'])->get();
        return view('devices.index', compact('devices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $devicegroups = DeviceGroup::with('devices')->withCount('devices')->get();
        return view('devices.create', compact('devicegroups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOrUpdateDeviceRequest $request)
    {
        if (Auth::user()->device_limit <= Auth::user()->devices->count()) {
            $request->session()->flash('flash_message', 'You have reached your device limit. Contact the administrator to assign you more');
            $request->session()->flash('flash_message_type', 'danger');
            return redirect()->back()->withInput();
        }
        $input = $request->validated();
        $device = Device::create($input);
        if (isset($input['device_group_ids']))
        {
            $device->device_groups()->sync($input['device_group_ids']);
        }
        Auth::user()->devices()->save($device);
        return redirect()->route('devices.show', $device);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Device $device)
    {
        return view('devices.show', compact("device"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Device $device)
    {
        $devicegroups = DeviceGroup::with('devices')->withCount('devices')->get();
        return view('devices.edit', compact('devicegroups', 'device'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateOrUpdateDeviceRequest $request, Device $device)
    {
        $input = $request->validated();
        $device->fill($input);
        if (isset($input['device_group_ids']))
        {
            $device->device_groups()->sync($input['device_group_ids']);
        } else {
            $device->device_groups()->sync([]);
        }
        $device->save();
        return redirect()->route('devices.show', $device);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Device $device)
    {
        $device->delete();
        return redirect()->route('devices.index');
    }

    public function export()
    {
        $headers = [
                'Cache-Control'       => 'must-revalidate, post-check=0, pre-check=0'
            ,   'Content-type'        => 'text/csv'
            ,   'Content-Disposition' => 'attachment; filename=devices.csv'
            ,   'Expires'             => '0'
            ,   'Pragma'              => 'public'
        ];

        $devices = Device::with(['sales', 'device_groups'])->get();

        $data = $devices->map(function ($device)
        {
            return [
                $device->name, 
                $device->created_at, 
                $device->is_active ? 'Active' : 'Disabled',
                $device->sales->count(),
                $device->sales->sum('total'),
                implode($device->device_groups->pluck('name')->toArray(), ","),
            ];
        })->toArray();

        array_unshift($data, ['Device', 'Date added', 'Status', 'Sales', 'Gross', 'Groups']);

        $callback = function() use ($data) 
        {
            $FH = fopen('php://output', 'w');
            foreach ($data as $row) { 
                fputcsv($FH, $row);
            }
            fclose($FH);
        };

        return Response::stream($callback, 200, $headers);
    }
}

resources/views/devices/create.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="company name">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Add device</h3>
                            </div>
                            <form method="POST" action="{{ route('devices.store') }}" enctype="multipart/form-data">
                                @csrf

                                @include('includes.forminputfields',['fieldname' => 'name', 'fieldtype' => 'text', 'attributes' => 'required autofocus'])

                                @include('includes.forminputfields',[
                                    'fieldname' => 'is_active',
                                    'fieldtype' => 'select', 
                                    'fieldlabel' => 'Status', 
                                    'fieldoptions' => [
                                        '0' => 'Disabled',
                                        '1' => 'Active'
                                    ],
                                    'attributes' => 'required'
                                ])

                                <div class="form-group row">
                                    <p class="text-center">
                                        @if ($errors->has('device_group_ids.*'))
                                            <span class="text-danger error">
                                                <strong>{{ $errors->first('device_group_ids.*') }}</strong>
                                            </span>
                                        @endif
                                    </p>
                                    <div class="table-responsive m-b-40">
                                        <table class="table table-borderless table-data2 datatable">
                                            <thead>
                                                <tr>
                                                    <th>Assign to Device Groups (Optional)</th>
                                                    <th>Device count</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($devicegroups as $devicegroup)
                                                    <tr>
                                                        <td>
                                                            <div class="form-group row">
                                                                <div class="col-md-1">
                                                                    <input id="group{{$devicegroup->id}}" type="checkbox" class="form-check-input" name="device_group_ids[]" value="{{$devicegroup->id}}">
                                                                </div>
                                                                <label for="group{{$devicegroup->id}}" class="form-check-label col-md-4">{{$devicegroup->name}}</label>
                                                            </div>
                                                        </td>
                                                        <td>{{$devicegroup->devices_count}}</td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                @include('includes.forminputfields',['fieldtype' => 'submit', 'fieldlabel' => 'Add device'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/devices/edit.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="company name">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Device 1</h3>
                            </div>
                            <form method="POST" action="{{ route('devices.update', $device) }}">
                                @csrf
                                @method('PUT')

                                @include('includes.forminputfields',['fieldname' => 'name', 'fieldtype' => 'text', 'fielddefault' => $device->name, 'attributes' => 'required autofocus'])

                                @include('includes.forminputfields',[
                                    'fieldname' => 'is_active',
                                    'fieldtype' => 'select', 
                                    'fieldlabel' => 'Status',
                                    'fielddefault' => $device->is_active,
                                    'fieldoptions' => [
                                        '0' => 'Disabled',
                                        '1' => 'Active'
                                    ],
                                    'attributes' => 'required'
                                ])

                                <div class="form-group row">
                                    <p class="text-center">
                                        @if ($errors->has('device_group_ids.*'))
                                            <span class="text-danger error">
                                                <strong>{{ $errors->first('device_group_ids.*') }}</strong>
                                            </span>
                                        @endif
                                    </p>
                                    <div class="table-responsive m-b-40">
                                        <table class="table table-borderless table-data2 datatable">
                                            <thead>
                                                <tr>
                                                    <th>Assign to Device Groups (Optional)</th>
                                                    <th>Device count</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($devicegroups as $devicegroup)
                                                    <tr>
                                                        <td>
                                                            <div class="form-group row">
                                                                <div class="col-md-1">
                                                                    <input id="group{{$devicegroup->id}}" type="checkbox" class="form-check-input" {{($devicegroup->devices->contains($device)) ? 'checked' : ''}} name="device_group_ids[]" value="{{$devicegroup->id}}">
                                                                </div>
                                                                <label for="group{{$devicegroup->id}}" class="form-check-label col-md-4">{{$devicegroup->name}}</label>
                                                            </div>
                                                        </td>
                                                        <td>{{$devicegroup->devices_count}}</td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                @include('includes.forminputfields',['fieldtype' => 'submit', 'fieldlabel' => 'Edit device'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/devices/index.blade.php
@extends('layouts.admin')

@section('admincontent')

<div class="row">
    <div class="col-md-12">
        @include('includes.devices')
    </div>
</div>

@endsection

resources/views/devices/show.blade.php
@extends('layouts.admin')

@section('admincontent')

<div class="section__content section__content--p30">
    <div class="container-fluid">
        @component('components.notification', ['class' => 'info'])
            API Token: {{$device->api_token}}
        @endcomponent

        <div class="row m-t-30">
            <div class="col-lg-12">
                <!-- TOP CAMPAIGN-->
                <div class="top-campaign">
                    <h3 class="title-3 m-b-30">details</h3>
                    <div class="table-responsive">
                        <table class="table table-top-campaign">
                            <tbody>
                                <tr>
                                    <td>Name</td>
                                    <td>{{$device->name}}</td>
                                </tr>
                                <tr>
                                    <td>Status</td>
                                    <td>
                                        <span class="status--{{$device->is_active ? 'process' : 'denied'}}">{{$device->is_active ? 'Active' : 'Disabled'}}</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Sales</td>
                                    <td>{{$device->sales->count()}}</td>
                                </tr>
                                <tr>
                                    <td>Gross</td>
                                    <td>{{$device->sales->sum('total')}}</td>
                                </tr>
                                <tr>
                                    <td>Date added</td>
                                    <td>{{$device->created_at}}</td>
                                </tr>
                                <tr>
                                    <td>Groups</td>
                                    <td>
                                        <ul class="list-unstyled">
                                            @foreach ($device->device_groups as $device_group)
                                                <li>
                                                    <a href="{{route('devicegroups.show', $device_group)}}">
                                                        <span class="block-email">{{$device_group->name}}</span>
                                                    </a>
                                                </li>
                                                <br>
                                            @endforeach
                                        </ul>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <a class="au-btn au-btn-icon au-btn--blue2 au-btn--small" href="{{route('devices.edit', $device)}}">
                        <i class="zmdi zmdi-edit"></i>edit device</a>
                </div>
                <!-- END TOP CAMPAIGN-->
            </div>
        </div>
    </div>
</div>

@include('includes.sales', ['sales' => $device->sales])

@endsection