routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
Route::post('/dashboard/top-grossing-products', 'DashboardController@top_grossing_products')->name('dashboard.top_grossing_products');
Route::post('/dashboard/top-selling-products', 'DashboardController@top_selling_products')->name('dashboard.top_selling_products');
Route::post('/dashboard/sales-gross-chart', 'DashboardController@sales_gross_chart')->name('dashboard.sales_gross_chart');
Route::post('/dashboard/device-sales', 'DashboardController@device_sales')->name('dashboard.device_sales');
Route::get('/dashboard/export-devices-csv', 'DashboardController@export_devices_csv')->name('dashboard.export_devices_csv');

Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

Route::get('/devices/export', 'DeviceController@export')->name('devices.export');
Route::resource('devices', 'DeviceController');

Route::resource('users', 'UserController', ['except' => ['create', 'store']]);

Route::get('/devicegroups/export', 'DeviceGroupController@export')->name('devicegroups.export');
Route::resource('devicegroups', 'DeviceGroupController');


Route::resource('usergroups', 'UserGroupController');

Route::get('/sales/{sale}/download', 'SaleController@download')->name('sales.download');
Route::get('/sales/export', 'SaleController@export')->name('sales.export');
Route::resource('sales', 'SaleController', ['only' => ['index', 'show']]);

Route::get('/products/export', 'ProductController@export')->name('products.export');
Route::resource('products', 'ProductController', ['only' => ['index', 'show']]);

resources/views/includes/adminsidebar.blade.php
<ul class="list-unstyled navbar__list">
    <li class="has-sub">
        <a class="js-arrow" href="#">
            <i class="fas fa-tachometer-alt"></i>Dashboard
            <span class="arrow">
                <i class="fas fa-angle-down"></i>
            </span>
        </a>
        <ul class="list-unstyled navbar__sub-list js-sub-list">
            <li>
                <a href="{{route('dashboard.index')}}">Home</a>
            </li>
            <li>
                <a href="{{route('sales.index')}}">Sales</a>
            </li>
            <li>
                <a href="{{route('products.index')}}">Products</a>
            </li>
        </ul>
    </li>
    <li class="has-sub">
        <a class="js-arrow" href="#">
            <i class="fas fa-microchip"></i>Devices
            <span class="arrow">
                <i class="fas fa-angle-down"></i>
            </span>
        </a>
        <ul class="list-unstyled navbar__sub-list js-sub-list">
            <li>
                <a href="{{route('devices.index')}}">Device management</a>
            </li>
            <li>
                <a href="{{route('devicegroups.index')}}">Device groups</a>
            </li>
        </ul>
    </li>
    <li class="has-sub">
        <a class="js-arrow" href="#">
            <i class="fas fa-users"></i>Users
            <span class="arrow">
                <i class="fas fa-angle-down"></i>
            </span>
        </a>
        <ul class="list-unstyled navbar__sub-list js-sub-list">
            <li>
                <a href="{{route('users.index')}}">Accounts</a>
            </li>
            <li>
                <a href="{{route('usergroups.index')}}">Groups</a>
            </li>
        </ul>
    </li>
    <li class="has-sub">
        <a class="js-arrow" href="#">
            <i class="fas fa-user"></i>Account
            <span class="arrow">
                <i class="fas fa-angle-down"></i>
            </span>
        </a>
        <ul class="list-unstyled navbar__sub-list js-sub-list">
            <li>
                <a href="{{route('profile.index')}}">Profile</a>
            </li>
        </ul>
    </li>
</ul>

resources/views/includes/authheader.blade.php
<link href="/css/auth.css" rel="stylesheet" media="all">
@if (Route::has('login'))
    <div class="top-right links">
        @auth
            <a href="{{ url('/home') }}">Home</a>
        @else
            <a href="{{ route('login') }}">Login</a>

            @if (Route::has('register'))
                <a href="{{ route('register') }}">Register</a>
            @endif
        @endauth
    </div>
@endif

resources/views/includes/breadcrumbs.blade.php
<div class="au-breadcrumb3">
    <div class="au-breadcrumb-left">
        <span class="au-breadcrumb-span">You are here:</span>
        <ul class="list-unstyled list-inline au-breadcrumb__list">
            <li class="list-inline-item active">
                <a href="/">Home</a>
            </li>
            @foreach (explode("/",Request::path()) as $path)
                @if ($path != "")
                    <li class="list-inline-item seprate">
                        <span>/</span>
                    </li>
                    <li class="list-inline-item">{{ucfirst($path)}}</li>
                @endif
            @endforeach
        </ul>
    </div>
</div>

resources/views/includes/devices.blade.php
<!-- DATA TABLE -->
<h3 class="title-5 m-b-35">Devices</h3>
<div class="table-data__tool">
    <div class="table-data__tool-left">
        <a class="au-btn au-btn-icon au-btn--blue2 au-btn--small" href="{{route('devices.export')}}" target="_blank">
            <i class="fa fa-file-excel"></i> Export CSV
        </a>
    </div>
    <div class="table-data__tool-right">
        @if (!isset($hide_add_device_link) || !$hide_add_device_link)
            <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{{route('devices.create')}}">
                <i class="zmdi zmdi-plus"></i>add device
            </a>
        @endif
    </div>
</div>
<div class="table-responsive table-responsive-data2">
    <table class="table table-data2 datatable">
        <thead>
            <tr>
                <th>name</th>
                <th>date added</th>
                <th>Status</th>
                <th>Sales</th>
                <th>groups</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($devices as $device)
                <tr class="tr-shadow">
                    <td>{{$device->name}}</td>
                    <td>{{$device->created_at}}</td>
                    <td>
                        <span class="status--{{$device->is_active ? 'process' : 'denied'}}">{{$device->is_active ? 'Active' : 'Disabled'}}</span>
                    </td>
                    <td>{{$device->sales->sum('total')}}</td>
                    <td>
                        <ul class="list-unstyled">
                            @foreach ($device->device_groups as $device_group)
                                <li class="m-b-20">
                                    <a href="{{route('devicegroups.show', $device_group)}}">
                                        <span class="block-email">{{$device_group->name}}</span>
                                    </a>
                                </li>
                            @endforeach
                        </ul>
                    </td>
                    <td>
                        <div class="table-data-feature">
                            <a href="{{route('devices.edit', $device)}}" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                <i class="zmdi zmdi-edit"></i>
                            </a>
                            <form action="{{route('devices.destroy', $device)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="item" type='submit' data-toggle="tooltip" data-placement="top" title="Delete">
                                    <i class="zmdi zmdi-delete"></i>
                                </button>
                            </form>
                            <a href="{{route('devices.show', $device)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                <i class="zmdi zmdi-more"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                <div class="spacer"></div>
            @endforeach
        </tbody>
    </table>
</div>
<!-- END DATA TABLE -->

resources/views/includes/forminputfields.blade.php
@if ($fieldtype == 'submit')
    <div class="form-group row mb-0">
        <div class="col-md-8 offset-md-2">
            <button type="submit" class="btn btn-primary btn-block">
                    {{ __(isset($fieldlabel) ? $fieldlabel : 'Submit') }}
            </button>
        </div>
    </div>
@else
    <div class="form-group row">
        @if (!isset($fieldlabel) || $fieldlabel != null)
            <label for="{{isset($fieldid) ? $fieldid : $fieldname}}" class="col-md-4 col-form-label text-md-right">{{ __(isset($fieldlabel) ? $fieldlabel : ucfirst($fieldname)) }}</label>
        @endif

        <div class="{{((isset($fieldlabel) && $fieldlabel == null) ? 'col-md-12' : 'col-md-6')}}">
            @if($fieldtype == 'image')
                <div class="col-sm-12 imgUp">
                    <div class="imagePreview"></div>
                    <label class="btn btn-dark">
                        Choose file to upload
                        <input type="file" class="uploadFile img{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" value="Upload Image" style="width: 0px;height: 0px;overflow: hidden;" id="{{isset($fieldid) ? $fieldid : $fieldname}}" name="{{$fieldname}}" {{isset($attributes) ? $attributes : ''}}>
                    </label>
                </div>
            @elseif($fieldtype == 'radio')
                <label class="switch switch-3d switch-primary mr-3">
                    <input id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="radio" class="switch-input form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" {{(isset($fielddefault) && $fielddefault) ? 'checked' : ''}} name="{{$fieldname}}"  value="{{$fieldvalue}}" {{isset($attributes) ? $attributes : ''}}>
                    <span class="switch-label"></span>
                    <span class="switch-handle"></span>
                </label>
            @elseif($fieldtype == 'checkbox')
                <label class="switch switch-3d switch-primary mr-3">
                    <input id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="checkbox" class="switch-input form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" {{(isset($fielddefault) && $fielddefault) ? 'checked' : ''}} name="{{$fieldname}}" value="{{$fieldvalue}}" {{isset($attributes) ? $attributes : ''}}>
                    <span class="switch-label"></span>
                    <span class="switch-handle"></span>
                </label>
            @elseif($fieldtype == 'select')
                <select id="{{isset($fieldid) ? $fieldid : $fieldname}}" class="form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" name="{{$fieldname}}" {{isset($attributes) ? $attributes : ''}}>
                        <option value="-1">{{ __(isset($fieldlabel) ? $fieldlabel : ucfirst($fieldname)) }}</option>    
                    @foreach ($fieldoptions as $optionvalue => $optionlabel)
                        <option value="{{$optionvalue}}" {{ (isset($fielddefault) && $fielddefault == $optionvalue) ? 'selected' : '' }}>{{$optionlabel}}</option>
                    @endforeach
                </select>
            @elseif($fieldtype == 'textarea')
                <textarea id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="{{$fieldtype}}" class="au-input au-input--full form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" name="{{$fieldname}}" {{isset($attributes) ? $attributes : ''}}>{{ isset($fielddefault) ? $fielddefault : old($fieldname) }}</textarea>
            @else
                <input id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="{{$fieldtype}}" class="au-input au-input--full form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" name="{{$fieldname}}" value="{{ isset($fielddefault) ? $fielddefault : old($fieldname) }}" {{isset($attributes) ? $attributes : ''}}>
            @endif

            @if ($errors->has($fieldname))
                <span class="text-danger error">
                    <strong>{{ $errors->first($fieldname) }}</strong>
                </span>
            @endif
        </div>
    </div>    
@endif

resources/views/includes/headertool.blade.php
<div class="account-wrap">
    <div class="account-item account-item--style2 clearfix js-item-menu">
        <div class="image">
            <img src="{{Auth::user()->imageUrl('picture')}}" alt="John Doe" />
        </div>
        <div class="content">
            <a class="js-acc-btn" href="#">{{Auth::user()->name}}</a>
        </div>
        <div class="account-dropdown js-dropdown">
            <div class="info clearfix">
                <div class="image">
                    <a href="#">
                        <img src="{{Auth::user()->imageUrl('picture')}}" alt="{{Auth::user()->name}}" />
                    </a>
                </div>
                <div class="content">
                    <h5 class="name">
                        <a href="#">{{Auth::user()->name}}</a>
                    </h5>
                    <span class="email">{{Auth::user()->email}}</span>
                </div>
            </div>
            <div class="account-dropdown__body">
                <div class="account-dropdown__item">
                    <a href="{{route('profile.index')}}"><i class="zmdi zmdi-account"></i>Profile</a>
                </div>
            </div>
            <div class="account-dropdown__footer">
                @include('includes.logout')
            </div>
        </div>
    </div>
</div>

resources/views/includes/logout.blade.php
<a href="{{ route('logout') }}"
    onclick="event.preventDefault();
                    document.getElementById('__user-logout-form').submit();">
    <i class="zmdi zmdi-power-off"></i>
    {{ __('Logout') }}
</a>

<form id="__user-logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>

resources/views/includes/modal.blade.php
<!-- modal medium -->
<div class="modal fade" id="modal_message" tabindex="-1" role="dialog" aria-labelledby="modal_title" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_title">{{{{$modal_title}}}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="modal_body">
                    {{$modal_body}}
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<!-- end modal medium -->

resources/views/includes/products.blade.php
<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">products</h3>
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <a class="au-btn au-btn-icon au-btn--blue2 au-btn--small" href="{{route('products.export')}}" target="_blank">
                    <i class="fa fa-file-excel"></i> Export CSV
                </a>
            </div>
            <div class="table-data__tool-right"></div>
        </div>
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2 datatable">
                <thead>
                    <tr>
                        <th>name</th>
                        <th>sold quantity</th>
                        <th>gross</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr class="tr-shadow">
                            <td>{{$product->name}}</td>
                            <td>{{$product->sold_quantity}}</td>
                            <td>{{$product->gross}}</td>
                            <td>
                                <div class="table-data-feature">
                                    <a href="{{route('products.show', $product)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                        <i class="zmdi zmdi-more"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <div class="spacer"></div>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>

resources/views/includes/saleproducts.blade.php
<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">sale products</h3>
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <div class="rs-select2--light rs-select2--md">
                    <select class="js-select2" name="property">
                        <option selected="selected">All Properties</option>
                        <option value="">CSV</option>
                        <option value="">PDF</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
                <div class="rs-select2--light rs-select2--sm">
                    <select class="js-select2" name="time">
                        <option selected="selected">Today</option>
                        <option value="">3 Days</option>
                        <option value="">1 Week</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
                <button class="au-btn-filter">
                    <i class="zmdi zmdi-filter-list"></i>filters</button>
            </div>
            <div class="table-data__tool-right">
                <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                    <select class="js-select2" name="type">
                        <option selected="selected">Export</option>
                        <option value="">Option 1</option>
                        <option value="">Option 2</option>
                    </select>
                    <div class="dropDownSelect2"></div>
                </div>
            </div>
        </div>
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2 datatable">
                <thead>
                    <tr>
                        <th>name</th>
                        <th>price</th>
                        <th>quantity</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($saleproducts as $saleproduct)
                        <tr class="tr-shadow">
                            <td>{{$saleproduct->product->name}}</td>
                            <td>{{$saleproduct->price}}</td>
                            <td>{{$saleproduct->quantity}}</td>
                            <td>
                                <div class="table-data-feature">
                                    <a href="{{route('products.show', $saleproduct->product)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                        <i class="zmdi zmdi-more"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <div class="spacer"></div>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>

resources/views/includes/sales.blade.php
<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">sales</h3>
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <a class="au-btn au-btn-icon au-btn--blue2 au-btn--small" href="{{route('sales.export')}}" target="_blank">
                    <i class="fa fa-file-excel"></i> Export CSV
                </a>
            </div>
            <div class="table-data__tool-right"></div>
        </div>
        <div class="table-responsive table-responsive-data2">
            <table class="table table-data2 datatable">
                <thead>
                    <tr>
                        <th>date</th>
                        <th>reference_number</th>
                        <th>device</th>
                        <th>products</th>
                        <th>total</th>
                        <th>options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($sales as $sale)
                        <tr class="tr-shadow">
                            <td>{{$sale->sale_date}}</td>
                            <td>{{$sale->reference_number}}</td>
                            <td>
                                <a href="{{route('devices.show', $sale->device)}}">
                                    <span class="block-email">{{$sale->device->name}}</span>
                                </a>
                            </td>
                            <td>{{$sale->sale_products->count()}}</td>
                            <td>{{$sale->total}}</td>
                            <td>
                                <div class="table-data-feature">
                                    <a href="{{route('sales.download', $sale)}}" class="item" data-toggle="tooltip" data-placement="top" title="Download Receipt">
                                        <i class="zmdi zmdi-download"></i>
                                    </a>
                                    <a href="{{route('sales.show', $sale)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                        <i class="zmdi zmdi-more"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <div class="spacer"></div>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>