routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
Route::post('/dashboard/top-grossing-products', 'DashboardController@top_grossing_products')->name('dashboard.top_grossing_products');
Route::post('/dashboard/top-selling-products', 'DashboardController@top_selling_products')->name('dashboard.top_selling_products');
Route::post('/dashboard/sales-gross-chart', 'DashboardController@sales_gross_chart')->name('dashboard.sales_gross_chart');
Route::post('/dashboard/device-sales', 'DashboardController@device_sales')->name('dashboard.device_sales');
Route::get('/dashboard/export-devices-csv', 'DashboardController@export_devices_csv')->name('dashboard.export_devices_csv');

Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

Route::get('/devices/export', 'DeviceController@export')->name('devices.export');
Route::resource('devices', 'DeviceController');

Route::resource('users', 'UserController', ['except' => ['create', 'store']]);

Route::get('/devicegroups/export', 'DeviceGroupController@export')->name('devicegroups.export');
Route::resource('devicegroups', 'DeviceGroupController');


Route::resource('usergroups', 'UserGroupController');

Route::get('/sales/{sale}/download', 'SaleController@download')->name('sales.download');
Route::get('/sales/export', 'SaleController@export')->name('sales.export');
Route::resource('sales', 'SaleController', ['only' => ['index', 'show']]);

Route::get('/products/export', 'ProductController@export')->name('products.export');
Route::resource('products', 'ProductController', ['only' => ['index', 'show']]);

app/DeviceGroup.php
<?php

namespace App;

use App\Device;
use App\Traits\HasUuid;
use Illuminate\Database\Eloquent\Model;

class DeviceGroup extends Model
{
    use HasUuid;

    public $incrementing = false;
    
    protected $fillable = ['name'];
    
    public function devices()
    {
        return $this->belongsToMany(Device::class, 'devices_device_groups', 'device_group_id', 'device_id');
    }

    public function getTotalSalesAttribute()
    {
        return $this->devices->sum(function ($device) { return $device->sales->count(); });
    }

    public function getGrossSalesAttribute()
    {
        return $this->devices->sum(function ($device) { return $device->sales->sum('total'); });
    }
}

app/Http/Controllers/DeviceGroupController.php
<?php

namespace App\Http\Controllers;

use App\DeviceGroup;
use Illuminate\Http\Request;
use App\Http\Requests\CreateOrUpdateDeviceGroupRequest;
use Response;

class DeviceGroupController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $devicegroups = DeviceGroup::with('devices.sales')->withCOunt('devices')->get();
        return view('devicegroups.index', compact('devicegroups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('devicegroups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOrUpdateDeviceGroupRequest $request)
    {
        $input = $request->validated();
        $devicegroup = DeviceGroup::create($input);
        return redirect()->route('devicegroups.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(DeviceGroup $devicegroup)
    {
        $devicegroup->load('devices');
        return view('devicegroups.show', compact('devicegroup'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(DeviceGroup $devicegroup)
    {
        return view('devicegroups.edit', compact('devicegroup'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateOrUpdateDeviceGroupRequest $request,DeviceGroup $devicegroup)
    {
        $input = $request->validated();
        $devicegroup->fill($input)->save();
        return redirect()->route('devicegroups.show', $devicegroup);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(DeviceGroup $devicegroup)
    {
        $devicegroup->delete();
        return redirect()->route('devicegroups.index');
    }

    public function export()
    {
        $headers = [
                'Cache-Control'       => 'must-revalidate, post-check=0, pre-check=0'
            ,   'Content-type'        => 'text/csv'
            ,   'Content-Disposition' => 'attachment; filename=devicegroups.csv'
            ,   'Expires'             => '0'
            ,   'Pragma'              => 'public'
        ];

        $devicegroups = DeviceGroup::with('devices')->get();

        $data = $devicegroups->map(function ($devicegroup)
        {
            return [
                $devicegroup->name, 
                $devicegroup->devices->count(), 
                $devicegroup->total_sales,
                $devicegroup->gross_sales,
            ];
        })->toArray();

        array_unshift($data, ['Device Group', 'Device count', 'Sales', 'Gross']);

        $callback = function() use ($data) 
        {
            $FH = fopen('php://output', 'w');
            foreach ($data as $row) { 
                fputcsv($FH, $row);
            }
            fclose($FH);
        };

        return Response::stream($callback, 200, $headers);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\AdminUpdateUserRequest;

class UserController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withCount('devices')->get();
        return view('users.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $user->load(['devices', 'devices.device_groups']);
        return view('users.show', compact("user"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact("user"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUpdateUserRequest $request,User $user)
    {
        $input = $request->validated();
        $user->fill($input)->save();
        return redirect()->route('users.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user == Auth::user()->id) {
            return redirect()->back()->withErrors(['user' => 'Cannot delete that user'])->withInput();
        }
        return redirect()->route('users.index');
    }
}

resources/views/devicegroups/create.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="company name">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Add Device Group</h3>
                            </div>
                            <form method="POST" action="{{ route('devicegroups.store') }}">
                                @csrf

                                @include('includes.forminputfields',['fieldname' => 'name', 'fieldtype' => 'text', 'attributes' => 'required autofocus'])

                                @include('includes.forminputfields',['fieldtype' => 'submit', 'fieldlabel' => 'Add device group'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/devicegroups/edit.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="company name">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Device group 1</h3>
                            </div>
                            <form method="POST" action="{{ route('devicegroups.update', $devicegroup) }}">
                                @csrf
                                @method('PUT')

                                @include('includes.forminputfields',['fieldname' => 'name', 'fieldtype' => 'text', 'fielddefault' => $devicegroup->name, 'attributes' => 'required autofocus'])

                                @include('includes.forminputfields',['fieldtype' => 'submit', 'fieldlabel' => 'Edit device group'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/devicegroups/index.blade.php
@extends('layouts.admin')

@section('admincontent')

<div class="row">
    <div class="col-md-12">
        <!-- DATA TABLE -->
        <h3 class="title-5 m-b-35">Device groups</h3>
        <div class="table-data__tool">
            <div class="table-data__tool-left">
                <a class="au-btn au-btn-icon au-btn--blue2 au-btn--small" href="{{route('devicegroups.export')}}" target="_blank">
                    <i class="fa fa-file-excel"></i> Export CSV
                </a>
            </div>
            <div class="table-data__tool-right"></div>
        </div>
        <div class="table-responsive table-responsive-data">
            <table class="table table-data2 datatable">
                <thead>
                    <tr>
                        <th>name</th>
                        <th>devices</th>
                        <th>Sales</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($devicegroups as $devicegroup)
                        <tr class="tr-shadow">
                            <td>{{$devicegroup->name}}</td>
                            <td>
                                <span class="status--{{$devicegroup->devices_count > 0 ? 'process' : 'denied'}}">{{$devicegroup->devices_count}}</span>
                            </td>
                            <td>{{$devicegroup->total_sales}}</td>
                            <td>
                                <div class="table-data-feature">
                                    <a href="{{route('devicegroups.edit', $devicegroup)}}" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                        <i class="zmdi zmdi-edit"></i>
                                    </a>
                                    <form action="{{route('devicegroups.destroy', $devicegroup)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                            <i class="zmdi zmdi-delete"></i>
                                        </button>
                                    </form>
                                    <a href="{{route('devicegroups.show', $devicegroup)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                        <i class="zmdi zmdi-more"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>    
                        <div class="spacer"></div>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE -->
    </div>
</div>

@endsection

resources/views/devicegroups/show.blade.php
@extends('layouts.admin')

@section('admincontent')

<h3>{{$devicegroup->name}}</h3>
@include('includes.devices', ['devices' => $devicegroup->devices, 'hide_add_device_link' => true])

@endsection